"""empty message

Revision ID: 013d56880ffb
Revises: 5d12219acebe
Create Date: 2024-07-28 14:37:16.079333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '013d56880ffb'
down_revision = '5d12219acebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta', sa.JSON(), nullable=True))
        batch_op.drop_column('unit')
        batch_op.drop_column('raw')
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('raw', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('unit', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('meta')

    # ### end Alembic commands ###
