"""empty message

Revision ID: 5d12219acebe
Revises: 84d2fc531bc6
Create Date: 2024-07-28 13:42:01.376857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d12219acebe'
down_revision = '84d2fc531bc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('unit', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('raw', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.drop_column('raw')
        batch_op.drop_column('unit')
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
