"""empty message

Revision ID: 84d2fc531bc6
Revises: 5100f4571562
Create Date: 2024-07-26 14:23:16.400195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84d2fc531bc6'
down_revision = '5100f4571562'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_index('ix_ingredients_name')
        batch_op.create_index(batch_op.f('ix_ingredients_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredients_name'))
        batch_op.create_index('ix_ingredients_name', ['name'], unique=True)

    # ### end Alembic commands ###
